default_install_hook_types: [commit-msg]

repos:
  - repo: local
    hooks:
      - id: un-author
        name: Strip co-authors
        entry: python un_author.py
        language: python
        stages: [commit-msg]
